############################################################
# Dockerfile to build sandbox for executing user code
# Based on Ubuntu
############################################################

FROM ubuntu:latest
MAINTAINER MAYANK SHARMA
FROM gcc:latest
RUN apt-get -y update
RUN apt-get -y upgrade





