server:
  port: 8080
  ssl:
    #key store config
    key-alias: montooboss
    key-store-password: 1234@1234
    key-store: /home/montooboss/Desktop/GITHUB/CodeMaster/codeMasterAPI/src/main/resources/CodeMasterKeys.jks
    key-store-type: JKS
    key-password: 1234@1234
    #trust store config
#    trust-store: /home/montooboss/Desktop/GITHUB/CodeMaster/codeMasterAPI/src/main/resources/trust-store.p12
#    trust-store-password: 1234@1234
#    trust-store-type: PKCS12



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codeMasterApi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: montooboss
    password: Mayank3#@sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
  rabbitmq:
    addresses: localhost:5672
    queue_name: codeMasterQueue
    routing_key: da5b5056c7c4866d687d9bdf63cda7bd
    exchange_name: codeMasterExchange



jwt:
  expiration:
    time: 86400

